// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "13c50430-3fe1-41ca-967b-ef5348966a99");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1746923150);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1746924115);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1746923149);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{96090193-68d8-450f-81f3-6db60a7c2dec}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1746923148);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 152);
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", "{\"CAISBmxlbmRnbw\":[1746923659141,1746924114917],\"CAISEmVuZXJneWJpbGxjcnVuY2hlcg\":[1746924114918],\"CAISC2ZpbmFuY2VidXp6\":[1746924114919]}");
user_pref("browser.newtabpage.activity-stream.discoverystream.thumbsUpDown.region-thumbs-config", "US");
user_pref("browser.newtabpage.activity-stream.impressionId", "{b8b6e80a-6c31-4b57-a14c-cd8218126de8}");
user_pref("browser.newtabpage.activity-stream.newtabShortcuts.refresh", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1746923149);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1746924121211");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1746925946211");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1746923150308");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1746944750308");
user_pref("browser.search.region", "US");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250414224040");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1746924115");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20250414224040");
user_pref("browser.startup.homepage_override.mstone", "137.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1746924115);
user_pref("browser.tabs.groups.enabled", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1746924115);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captchadetection.lastSubmission", 1746923);
user_pref("datareporting.dau.cachedUsageProfileID", "6499a4b4-01cf-4ab9-861f-166e3a6914bd");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1746923149506");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "137.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "dc452cf206e341d8a2eb0a3913317c9c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECMCXpQT7NU1GBAh/0MvGjHknMA==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250414224040");
user_pref("extensions.lastAppVersion", "137.0.2");
user_pref("extensions.lastPlatformVersion", "137.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ba2cc73e-3eae-4cd5-a50f-effd57543bbc\",\"pictureinpicture@mozilla.org\":\"a9fc8d59-b500-4cc4-9171-74a6f1921ab2\",\"screenshots@mozilla.org\":\"f838ee7a-076e-4ccd-a92d-efe1e61280bd\",\"webcompat-reporter@mozilla.org\":\"5c3d6f70-1a95-44f7-ba64-596e2427c4b8\",\"webcompat@mozilla.org\":\"00271d5a-dfb4-4931-91d0-4765e7e2adfc\",\"default-theme@mozilla.org\":\"8ffb3456-403e-4ddb-8926-0655b604a254\",\"addons-search-detection@mozilla.com\":\"9de6818a-b55e-4487-908d-6a053bf760fc\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.migrations.latest", 0);
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"us-rollout-compact-layout-thumbs-updown\",\"branch\":{\"slug\":\"rollout\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"US Rollout: Compact Layout + Thumbs Up/Down\",\"userFacingDescription\":\"Rollout thumbs up/down feedback with a slightly compacted layout\",\"lastSeen\":\"2025-05-11T00:25:49.746Z\",\"featureIds\":[\"pocketNewtab\"],\"prefs\":[{\"name\":\"browser.newtabpage.activity-stream.discoverystream.thumbsUpDown.region-thumbs-config\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"regionThumbsUpDownConfig\",\"originalValue\":null},{\"name\":\"browser.newtabpage.activity-stream.discoverystream.thumbsUpDown.searchTopsitesCompact\",\"branch\":\"user\",\"featureId\":\"pocketNewtab\",\"variable\":\"thumbsUpDownCompactLayout\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.regionThumbsUpDownConfig", "US");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.thumbsUpDownCompactLayout", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2025-05-11T00:25:49.732Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECFfVE3CLTEGQBAiGJ/EGhpXowQ==");
user_pref("toolkit.startup.last_success", 1746924114);
user_pref("toolkit.telemetry.cachedClientID", "4740209d-b152-4c7b-9cce-eda13f535f24");
user_pref("toolkit.telemetry.cachedProfileGroupID", "d8d9b04b-7e29-4911-a909-bf60a0cbdf43");
user_pref("toolkit.telemetry.previousBuildID", "20250414224040");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
